include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    unnecessary_null_comparison: error
    dead_code: error
  exclude:
    - build/**
    - "**/*.g.dart"
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    public_member_api_docs: true
    lines_longer_than_80_chars: true
    always_use_package_imports: true
    directives_ordering: true
    unawaited_futures: true
